#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s pasos%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  Tú manejas el navegador; este wizard te dice exactamente qué hacer y\n' "$DIM"
  printf '  guarda los valores que vas pegando de vuelta. Puedes parar en cualquier\n'
  printf '  momento con Ctrl-C y retomarlo después: recuerda lo que ya guardaste.%s\n' "$RESET"
  pause "¿Listo para empezar?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Paso %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ abriendo%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "no se pudo abrir un navegador; entra manualmente: $url"; fi
  } >/dev/null 2>&1 || warn "no se pudo abrir un navegador; entra manualmente: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Presiona Enter para continuar}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "se omitió el secret de GitHub $name: gh no está listo; configúralo después"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "se omitió la variable de GitHub $name; gh no está listo; configúrala después"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Configuración completa%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "se guardaron ${#WRITTEN_ENV[@]} valor(es) en $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "se configuraron ${#WRITTEN_SECRET[@]} secret(s) de GitHub: ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "queda pendiente hacer a mano:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10
ENV_FILE=".env.production"

banner "FitApp → primer deploy a Railway"

# ── Stage 1: cuenta y proyecto ──────────────────────────────────────────────
stage "Railway: cuenta y proyecto"
say "Vamos a crear el proyecto en Railway y conectarlo a szcris001/fitapp."
say "Al final de este wizard vas a tener la API y el Web corriendo en URLs"
say "*.up.railway.app — el dominio propio (Cloudflare) se hace después, aparte."
open_url "https://railway.app/new"
step "Si no tienes cuenta, entra con tu cuenta de GitHub (así queda conectada de una)."
step "Elige 'Deploy from GitHub repo' → autoriza Railway sobre tu cuenta si lo pide"
step "→ selecciona el repo 'szcris001/fitapp'."
step "Railway va a intentar detectar un servicio automáticamente: cuando te pregunte"
step "qué desplegar, cancela/ignora esa detección — los servicios los agregamos a mano"
step "en los siguientes pasos, porque este repo tiene dos Dockerfiles distintos"
step "(apps/api/Dockerfile y apps/web/Dockerfile), no uno solo en la raíz."
step "Ponle un nombre al proyecto, por ejemplo 'fitapp-production'."
confirm "¿Ya tienes el proyecto vacío creado y abierto en el dashboard?" || true

# ── Stage 2: Postgres y Redis ────────────────────────────────────────────────
stage "Railway: Postgres y Redis"
say "Dentro del proyecto, agrega los dos plugins gestionados."
step "Click en '+ New' → 'Database' → 'Add PostgreSQL'."
step "Click en '+ New' → 'Database' → 'Add Redis'."
note "Railway los deja corriendo con una URL de conexión propia; no hace falta"
note "instalar nada más ni exponerlos — ya quedan privados dentro del proyecto."
pause "Cuando los dos aparezcan en el canvas del proyecto, seguimos."

# ── Stage 3: secretos locales ────────────────────────────────────────────────
stage "Generar secretos"
say "Estos dos los genero yo con openssl y los vamos a pegar en Railway más adelante."
say "También quedan guardados en .env.production (que está en .gitignore: nunca se sube)."
JWT_SECRET=$(openssl rand -hex 32)
APP_DB_PASSWORD=$(openssl rand -hex 24)
write_env JWT_SECRET "$JWT_SECRET"
write_env APP_DB_PASSWORD "$APP_DB_PASSWORD"
note "JWT_SECRET:      $JWT_SECRET"
note "APP_DB_PASSWORD: $APP_DB_PASSWORD"
warn "Cópialos ahora a algún lado (o vuelve a este .env.production): los vas a pegar"
warn "como variables del servicio API en el próximo stage."
pause "Listo, los tengo a mano"

# ── Stage 4: variables sueltas de Postgres ──────────────────────────────────
stage "Railway: variables del plugin Postgres"
say "DATABASE_URL completa del plugin de Postgres es la conexión de SUPERUSUARIO."
say "FitApp usa RLS: la API debe conectarse con un rol propio (fitapp_app), no como"
say "superusuario. Por eso vamos a armar DATABASE_URL a mano con las variables"
say "sueltas del plugin, no copiando su DATABASE_URL completa."
step "Click en el servicio 'Postgres' → pestaña 'Variables'."
step "Confirma que existen (o anota el nombre exacto si Railway los llama distinto"
step "en tu proyecto) estos tres: PGHOST, PGPORT, PGDATABASE."
note "Si Railway los muestra con otro nombre en tu proyecto, usa esos nombres en las"
note "referencias \${{Postgres.NOMBRE}} del próximo stage — no hace falta copiarlos"
note "a mano ahora, solo confirmar que existen."
confirm "¿Ves PGHOST, PGPORT y PGDATABASE en las variables del plugin Postgres?" || \
  warn "Sigue igual: usa los nombres que sí veas ahí en el stage 5."

# ── Stage 5: servicio API ────────────────────────────────────────────────────
stage "Railway: crear el servicio API"
say "Ahora el servicio de la API, construido desde apps/api/Dockerfile."
step "En el proyecto: '+ New' → 'GitHub Repo' → 'szcris001/fitapp' (de nuevo, ahora"
step "sí para crear un servicio real)."
step "Abre el servicio nuevo → 'Settings' → 'Source':"
step "  - Root Directory: deja '/' (el Dockerfile usa contexto de la raíz del repo)"
step "  - Dockerfile Path: apps/api/Dockerfile"
step "En 'Settings' → 'Networking' → 'Volumes' → 'Add Volume':"
step "  - Mount path: /app/apps/api/uploads"
note "Sin ese volumen, avatares/logos/comprobantes se borran en cada redeploy."
step "En 'Variables', pega estas (una por línea, Railway las separa solo);"
step "reemplaza \${{Postgres...}} y \${{Redis...}} tal como Railway te las ofrezca al"
step "escribir '\${{' (autocompleta el nombre del servicio y la variable):"
say ""
say "  NODE_ENV=production"
say "  JWT_SECRET=$JWT_SECRET"
say "  APP_DB_PASSWORD=$APP_DB_PASSWORD"
say "  DATABASE_ADMIN_URL=\${{Postgres.DATABASE_URL}}"
say "  DATABASE_URL=postgresql://fitapp_app:\${{APP_DB_PASSWORD}}@\${{Postgres.PGHOST}}:\${{Postgres.PGPORT}}/\${{Postgres.PGDATABASE}}"
say "  REDIS_URL=\${{Redis.REDIS_URL}}"
say "  ANTHROPIC_API_KEY=<tu clave real de Anthropic>"
say "  FRONTEND_URL=http://localhost:3000"
say ""
note "No hace falta variable PORT: Railway detecta el puerto del EXPOSE del"
note "Dockerfile (3001) y le enruta el tráfico ahí."
note "FRONTEND_URL es un valor temporal: en el stage 8 lo cambiamos por la URL real"
note "del Web una vez que exista. Las claves de pasarelas (Stripe, Mercado Pago...)"
note "puedes dejarlas afuera por ahora y agregarlas cuando actives cada una — sin"
note "ellas la API arranca igual, esas pasarelas solo no van a funcionar todavía."
step "Guarda las variables → Railway va a construir y desplegar el servicio."
pause "Cuando el deploy termine (log verde / 'Success' en la pestaña Deployments)"

# ── Stage 6: URL pública de la API ──────────────────────────────────────────
stage "Railway: dominio de la API y healthcheck"
step "En el servicio API → 'Settings' → 'Networking' → 'Generate Domain'."
ask API_URL "Pega la URL que te dio Railway (ej. https://fitapp-api-production.up.railway.app):"
write_env RAILWAY_API_URL "$API_URL"
say "Verificando $API_URL/healthz ..."
if curl -sf -m 15 "$API_URL/healthz" | grep -q '"status":"ok"'; then
  say "✓ La API responde y ve la base de datos (RLS incluido: así arrancó con"
  say "  DATABASE_ADMIN_URL, migró, creó el rol fitapp_app, y ya está corriendo con"
  say "  DATABASE_URL nada más)."
else
  warn "No respondió 200 con status ok todavía. Puede tardar ~1 min el primer arranque"
  warn "(corre las migraciones antes de levantar el servidor). Revisa los logs del"
  warn "servicio en Railway (pestaña Deployments → View Logs) si sigue sin responder."
  confirm "¿Confirmas que ya responde y seguimos?" || pause "Ok, revisa los logs y vuelve a correr este wizard"
fi

# ── Stage 7: servicio Web ────────────────────────────────────────────────────
stage "Railway: crear el servicio Web"
say "Ahora el panel Next.js, construido desde apps/web/Dockerfile."
say "Next.js incrusta NEXT_PUBLIC_API_URL en el build: tiene que ir como variable"
say "Y como build argument, con el mismo valor."
step "'+ New' → 'GitHub Repo' → 'szcris001/fitapp' otra vez."
step "En el servicio nuevo → 'Settings' → 'Source':"
step "  - Root Directory: '/'"
step "  - Dockerfile Path: apps/web/Dockerfile"
step "En 'Settings' → busca 'Build Args' (o 'Docker Build Arguments' según la versión"
step "del dashboard) → agrega:"
say "    NEXT_PUBLIC_API_URL=${API_URL}/api"
step "En 'Variables' agrega la misma, como variable de runtime también:"
say "    NEXT_PUBLIC_API_URL=${API_URL}/api"
step "Guarda → espera a que termine el build (tarda más que la API, compila Next.js)."
pause "Cuando el deploy del Web termine"

# ── Stage 8: URL pública del Web y cierre del círculo con FRONTEND_URL ──────
stage "Railway: dominio del Web y CORS"
step "En el servicio Web → 'Settings' → 'Networking' → 'Generate Domain'."
ask WEB_URL "Pega la URL del Web (ej. https://fitapp-web-production.up.railway.app):"
write_env RAILWAY_WEB_URL "$WEB_URL"
say "Verificando $WEB_URL/login ..."
if curl -sf -m 15 -o /dev/null "$WEB_URL/login"; then
  say "✓ El panel carga."
else
  warn "No respondió 200 todavía; puede seguir compilando. Revisa los logs si tarda."
fi
say ""
say "Ahora sí, cerramos el círculo: la API solo acepta pedidos del navegador cuyo"
say "origen sea exactamente FRONTEND_URL (CORS de producción)."
step "Vuelve al servicio API → 'Variables' → edita FRONTEND_URL:"
say "    FRONTEND_URL=$WEB_URL"
note "(sin '/' al final)"
step "Guarda → la API se reinicia sola con el valor nuevo (no hace falta reconstruir)."
pause "Cuando el redeploy de la API termine"
say "Prueba de humo: entra a $WEB_URL/login, y si ya tienes un gym registrado,"
say "inicia sesión. Si es la primera vez, usa el flujo de registro desde ahí mismo."
confirm "¿Cargó el login y (si probaste) pudiste iniciar sesión sin error de CORS?" || \
  warn "Si ves un error de CORS en la consola del navegador, revisa que FRONTEND_URL"

# ── Stage 9: RAILWAY_TOKEN y environment de GitHub ──────────────────────────
stage "GitHub: token de Railway y aprobación de producción"
say "Esto es para que el deploy automático (git push a master) funcione más adelante."
open_url "https://railway.app/account/tokens"
step "'Create Token' → dale un nombre (ej. 'github-actions-fitapp') → copia el token."
ask_secret RAILWAY_TOKEN "Pega el token de Railway:"
set_secret RAILWAY_TOKEN "$RAILWAY_TOKEN"
say ""
say "Y el gate de aprobación manual antes de cada deploy a producción:"
open_url "https://github.com/szcris001/fitapp/settings/environments"
step "Si no existe, crea un environment llamado exactamente 'production'."
step "Dentro de él, en 'Required reviewers', agrégate a ti mismo."
confirm "¿Ya existe el environment 'production' con vos como reviewer requerido?" || \
  warn "Sin esto, el job de deploy queda esperando tu aprobación manual la primera vez"

# ── Stage 10: cierre ─────────────────────────────────────────────────────────
stage "Listo — qué falta activar y qué queda para después"
say "Con RAILWAY_TOKEN ya en GitHub Secrets, dile a Claude 'ya tengo el token' para"
say "que descomente el bloque de Railway en .github/workflows/deploy.yml y lo pruebe"
say "con un push a master (con la aprobación manual del stage anterior)."
say ""
say "Para después, no es parte de este wizard:"
note "  - Dominio propio + Cloudflare (por ahora quedan las URLs *.up.railway.app)"
note "  - Sentry: crear proyecto y pegar SENTRY_DSN en las variables de la API"
note "  - Antes de publicar la app móvil: cambiar la URL hardcodeada en"
note "    apps/mobile/src/lib/api.ts de la IP local a ${API_URL}/api"
note "    (ver docs/devops.md, sección Mobile)"
note "  - Activar cada pasarela de pago real cuando la vayas a usar (sus claves"
note "    quedaron fuera de las variables base del stage 5)"

finish
